#!/bin/sh

# Install usbmount using:
# sudo apt-get install usbmount
# Then move or copy this file to /etc/usbmount/mount.d

# 'DotStarPiPainter.py' must be running in the background; it can be launched
# in the /etc/rc.local script.  When a USB stick is inserted, this issues
# SIGUSR1 signal to that process:
usr/bin/pkill -SIGUSR1 -f DotStarPiPainter.py
